const scenarios = [
  ["PAY-1042","Payment failed","Bank timeout","UPI","Yes",0,"retry",1899,0.94,true],
  ["PAY-1047","Payment failed","Insufficient funds","Card","Yes",1,"link",4999,0.89,true],
  ["CHK-2071","Checkout abandoned","Price comparison","UPI","Yes",0,"link",1299,0.76,true],
  ["INV-3088","Invoice overdue","Cash-flow delay","Netbanking","Yes",0,"human",18500,0.84,true],
  ["PAY-1051","Payment failed","Issuer decline","Card","No",0,"stop",3199,0.91,false],
  ["CHK-2079","Checkout abandoned","Unknown intent","UPI","Yes",0,"review",2499,0.52,false],
  ["PAY-1063","Payment failed","Bank timeout","UPI","Yes",2,"stop",899,0.97,false],
  ["INV-3095","Invoice overdue","Dispute signal","Netbanking","Yes",0,"review",42000,0.66,false],
  ["PAY-1074","Payment failed","Expired card","Card","Yes",0,"link",7499,0.93,true],
  ["CHK-2086","Checkout abandoned","Delivery friction","UPI","No",0,"stop",999,0.79,false],
  ["PAY-1081","Payment failed","Bank timeout","UPI","Yes",0,"retry",2799,0.96,true],
  ["INV-3101","Invoice overdue","Cash-flow delay","Netbanking","Yes",1,"human",13200,0.87,true]
];
const actionText={retry:"Retry once when issuer recovers",link:"Send one secure payment link",human:"Create human recovery task",stop:"Stop — policy guardrail",review:"Route to human review"};
const rows=document.querySelector('#caseRows'); let cases=[]; let filter='all';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function buildCases(){return scenarios.map((s,i)=>{const [id,signal,reason,method,consent,attempts,action,amount,confidence,success]=s;let outcome=success?'recovered':action==='stop'?'stopped':'review';return {id,signal,reason,method,consent,attempts,action,amount,confidence,success,outcome,events:["Loss event ingested from payment timeline","Diagnosis created from event context",action==='stop'?"Guardrail blocked additional outreach":action==='review'?"Confidence below automation threshold":`Action approved: ${actionText[action]}`,success?"Recovery confirmed and ledger updated":"Case retained with no automated action"]}})}
function render(){const list=cases.filter(c=>filter==='all'||c.outcome===filter);rows.innerHTML=list.map(c=>`<tr><td><div class="case-id">${c.id}</div><div class="sub">${money(c.amount)} · ${c.method}</div></td><td>${c.signal}<div class="sub">${c.reason}</div></td><td>${Math.round(c.confidence*100)}% confidence<div class="sub">${c.reason}</div></td><td>${actionText[c.action]}</td><td><span class="pill ${c.outcome}">${c.outcome==='recovered'?'Recovered':c.outcome==='stopped'?'Protected':'Human review'}</span></td><td><button class="view" data-id="${c.id}">Why?</button></td></tr>`).join('')||'<tr class="empty"><td colspan="6">No matching cases.</td></tr>';document.querySelectorAll('.view').forEach(b=>b.onclick=()=>showDetail(b.dataset.id));document.querySelector('#ledgerSummary').textContent=`Showing ${list.length} of ${cases.length} assessed cases`;}
function updateMetrics(evaluation){const eligible=cases.filter(c=>c.outcome!=='stopped');const recovered=cases.filter(c=>c.success).reduce((a,c)=>a+c.amount,0);const atRisk=cases.reduce((a,c)=>a+c.amount,0);const protectedAmount=cases.filter(c=>c.outcome==='stopped').reduce((a,c)=>a+c.amount,0);const average=cases.reduce((a,c)=>a+c.confidence,0)/cases.length;document.querySelector('#atRisk').textContent=money(atRisk);document.querySelector('#recovered').textContent=money(recovered);document.querySelector('#protected').textContent=money(protectedAmount);document.querySelector('#confidence').textContent=Math.round((evaluation?.diagnosisAccuracy??average)*100)+'%';document.querySelector('#modelNote').textContent=evaluation?`${evaluation.heldOutRows} held-out cases · ${evaluation.trainingRows} training cases`:'mean diagnosis confidence';document.querySelector('#caseCount').textContent=`${cases.length} cases assessed`;document.querySelector('#recoveryRate').textContent=`${Math.round(recovered/eligible.reduce((a,c)=>a+c.amount,0)*100)}% of eligible revenue`;}
function showDetail(id){const c=cases.find(x=>x.id===id);document.querySelector('#detailTitle').textContent=c.id+' · '+money(c.amount);document.querySelector('#detailContent').innerHTML=`<div class="detail-body"><div class="detail-grid"><div><span>LOSS SIGNAL</span><b>${c.signal}</b></div><div><span>DIAGNOSIS</span><b>${c.reason}</b></div><div><span>CONFIDENCE</span><b>${Math.round(c.confidence*100)}%</b></div><div><span>POLICY CHECK</span><b>${c.consent==='Yes'&&c.attempts<2?'Passed':'Stopped'}</b></div></div><p class="explain">${explanation(c)}</p><div class="audit"><h3>IMMUTABLE AUDIT TRAIL</h3>${c.events.map((e,i)=>`<div class="audit-item"><time>09:${String(12+i*2).padStart(2,'0')}</time>${e}</div>`).join('')}</div></div>`;document.querySelector('#detailDialog').showModal()}
function explanation(c){if(c.action==='stop')return `RecoveryOS did not act. ${c.consent==='No'?'The customer has not given contact consent.':`This case already has ${c.attempts} prior attempts, which meets the hard stopping rule.`} This protects the customer and prevents an avoidable complaint.`;if(c.action==='review')return `The diagnosis confidence is below the 75% automation threshold${c.reason==='Dispute signal'?' and a dispute indicator is present':''}. A human receives this evidence instead of an automated outreach.`;return `The action is limited to ${c.action==='retry'?'one retry':'one compliant outreach'} because the case has ${c.attempts} prior recovery attempt${c.attempts===1?'':'s'}, consent is present, and the ${Math.round(c.confidence*100)}% diagnosis clears the 75% threshold.`}
async function run(){const btn=document.querySelector('#runButton'),status=document.querySelector('#batchStatus');btn.disabled=true;btn.textContent='Training + evaluating model…';status.textContent='Generating held-out recovery batch';status.className='status running';try{const response=await fetch('/api/batch');if(!response.ok)throw new Error('Demo API unavailable');const payload=await response.json();cases=payload.cases.map(c=>({...c,success:c.outcome==='recovered',events:['Loss event ingested from payment timeline',`Diagnosis created: ${c.reason} (${Math.round(c.confidence*100)}%)`,c.decisionReason,c.outcome==='recovered'?'Sandbox action executed with idempotency key':'Case retained without automated action']}));updateMetrics(payload.evaluation);render();btn.textContent='Batch complete ✓';status.textContent=`${cases.length} held-out cases · audit ledger created`;status.className='status done'}catch(error){cases=buildCases();updateMetrics();render();btn.textContent='Offline demo complete ✓';status.textContent='Offline fallback: 12 synthetic cases assessed';status.className='status done'}finally{btn.disabled=false}}
document.querySelector('#runButton').onclick=run;document.querySelector('#resetButton').onclick=()=>{cases=[];filter='all';rows.innerHTML='<tr class="empty"><td colspan="6">No batch run yet. Your audit trail will appear here.</td></tr>';['atRisk','recovered','protected'].forEach(id=>document.querySelector('#'+id).textContent='₹0');document.querySelector('#confidence').textContent='—';document.querySelector('#modelNote').textContent='diagnosis evaluation';document.querySelector('#caseCount').textContent='0 cases assessed';document.querySelector('#recoveryRate').textContent='0% of eligible revenue';document.querySelector('#ledgerSummary').textContent='Load the batch to generate decisions.';document.querySelector('#batchStatus').textContent='Ready to assess batch';document.querySelector('#batchStatus').className='status';const b=document.querySelector('#runButton');b.disabled=false;b.innerHTML='Run recovery batch <span>→</span>'};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#closeDialog').onclick=()=>document.querySelector('#detailDialog').close();
